// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game_service_config.proto

package game_service_config

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求参数
type GameServiceConfigRequest struct {
	GameId               int32    `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	GameAreaId           int32    `protobuf:"varint,2,opt,name=game_area_id,json=gameAreaId,proto3" json:"game_area_id,omitempty"`
	GameSign             string   `protobuf:"bytes,3,opt,name=game_sign,json=gameSign,proto3" json:"game_sign,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	GameDispatchId       int32    `protobuf:"varint,5,opt,name=game_dispatch_id,json=gameDispatchId,proto3" json:"game_dispatch_id,omitempty"`
	OpType               int32    `protobuf:"varint,6,opt,name=op_type,json=opType,proto3" json:"op_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameServiceConfigRequest) Reset()         { *m = GameServiceConfigRequest{} }
func (m *GameServiceConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GameServiceConfigRequest) ProtoMessage()    {}
func (*GameServiceConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9682838bfcd9ad2, []int{0}
}

func (m *GameServiceConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameServiceConfigRequest.Unmarshal(m, b)
}
func (m *GameServiceConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameServiceConfigRequest.Marshal(b, m, deterministic)
}
func (m *GameServiceConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameServiceConfigRequest.Merge(m, src)
}
func (m *GameServiceConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GameServiceConfigRequest.Size(m)
}
func (m *GameServiceConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameServiceConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameServiceConfigRequest proto.InternalMessageInfo

func (m *GameServiceConfigRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *GameServiceConfigRequest) GetGameAreaId() int32 {
	if m != nil {
		return m.GameAreaId
	}
	return 0
}

func (m *GameServiceConfigRequest) GetGameSign() string {
	if m != nil {
		return m.GameSign
	}
	return ""
}

func (m *GameServiceConfigRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *GameServiceConfigRequest) GetGameDispatchId() int32 {
	if m != nil {
		return m.GameDispatchId
	}
	return 0
}

func (m *GameServiceConfigRequest) GetOpType() int32 {
	if m != nil {
		return m.OpType
	}
	return 0
}

// 响应参数
type GameServiceConfigResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameServiceConfigResponse) Reset()         { *m = GameServiceConfigResponse{} }
func (m *GameServiceConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GameServiceConfigResponse) ProtoMessage()    {}
func (*GameServiceConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9682838bfcd9ad2, []int{1}
}

func (m *GameServiceConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameServiceConfigResponse.Unmarshal(m, b)
}
func (m *GameServiceConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameServiceConfigResponse.Marshal(b, m, deterministic)
}
func (m *GameServiceConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameServiceConfigResponse.Merge(m, src)
}
func (m *GameServiceConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GameServiceConfigResponse.Size(m)
}
func (m *GameServiceConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameServiceConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameServiceConfigResponse proto.InternalMessageInfo

func (m *GameServiceConfigResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*GameServiceConfigRequest)(nil), "game_service_config.GameServiceConfigRequest")
	proto.RegisterType((*GameServiceConfigResponse)(nil), "game_service_config.GameServiceConfigResponse")
}

func init() {
	proto.RegisterFile("game_service_config.proto", fileDescriptor_e9682838bfcd9ad2)
}

var fileDescriptor_e9682838bfcd9ad2 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0x87, 0x89, 0x9a, 0xd8, 0x0e, 0x2a, 0xb2, 0x8a, 0xa6, 0x16, 0x21, 0xf4, 0x94, 0x8b, 0x11,
	0xec, 0xd1, 0x93, 0x7f, 0x40, 0x72, 0xf1, 0x90, 0x7a, 0xf2, 0x12, 0xd6, 0x64, 0x1a, 0x17, 0xda,
	0xec, 0xba, 0xbb, 0x29, 0xe6, 0x19, 0x7d, 0x29, 0xd9, 0xd9, 0x1c, 0x23, 0x78, 0x9c, 0xef, 0xcb,
	0x6f, 0x32, 0x33, 0x0b, 0xb3, 0x86, 0x6f, 0xb1, 0x34, 0xa8, 0x77, 0xa2, 0xc2, 0xb2, 0x92, 0xed,
	0x5a, 0x34, 0x99, 0xd2, 0xd2, 0x4a, 0x76, 0x36, 0xa2, 0x16, 0x3f, 0x01, 0xc4, 0x2f, 0x7c, 0x8b,
	0x2b, 0x8f, 0x9f, 0x88, 0x16, 0xf8, 0xd5, 0xa1, 0xb1, 0xec, 0x12, 0x0e, 0x29, 0x23, 0xea, 0x38,
	0x48, 0x82, 0x34, 0x2c, 0x22, 0x57, 0xe6, 0x35, 0x4b, 0xe0, 0x88, 0x04, 0xd7, 0xc8, 0x9d, 0xdd,
	0x23, 0x0b, 0x8e, 0x3d, 0x68, 0xe4, 0x79, 0xcd, 0xe6, 0x30, 0xf5, 0xbf, 0x13, 0x4d, 0x1b, 0xef,
	0x27, 0x41, 0x3a, 0x2d, 0x26, 0x0e, 0xac, 0x44, 0xd3, 0xb2, 0x73, 0x08, 0x77, 0x7c, 0xd3, 0x61,
	0x7c, 0x40, 0xc2, 0x17, 0x2c, 0x85, 0x53, 0x8a, 0xd4, 0xc2, 0x28, 0x6e, 0xab, 0x4f, 0xd7, 0x38,
	0xa4, 0xc6, 0x27, 0x8e, 0x3f, 0x0f, 0x38, 0xaf, 0xdd, 0x5c, 0x52, 0x95, 0xb6, 0x57, 0x18, 0x47,
	0x7e, 0x2e, 0xa9, 0xde, 0x7a, 0x85, 0x8b, 0x25, 0xcc, 0x46, 0x96, 0x31, 0x4a, 0xb6, 0x06, 0xd9,
	0x05, 0x44, 0x1a, 0x4d, 0xb7, 0xb1, 0xb4, 0xcc, 0xa4, 0x18, 0xaa, 0xbb, 0x6f, 0x38, 0x7e, 0x95,
	0x56, 0xac, 0xfb, 0x21, 0xc6, 0x1a, 0x88, 0x3c, 0x60, 0x37, 0xd9, 0xd8, 0x39, 0xff, 0xba, 0xd7,
	0x55, 0xf6, 0xdf, 0xcf, 0xfd, 0x44, 0x8f, 0xd7, 0xef, 0xf3, 0xec, 0x96, 0x1e, 0xe7, 0x7e, 0x24,
	0xf8, 0x11, 0x91, 0x5a, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xe9, 0xff, 0xe5, 0x76, 0xd4, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NotifyServiceClient is the client API for NotifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotifyServiceClient interface {
	Notify(ctx context.Context, in *GameServiceConfigRequest, opts ...grpc.CallOption) (*GameServiceConfigResponse, error)
}

type notifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifyServiceClient(cc grpc.ClientConnInterface) NotifyServiceClient {
	return &notifyServiceClient{cc}
}

func (c *notifyServiceClient) Notify(ctx context.Context, in *GameServiceConfigRequest, opts ...grpc.CallOption) (*GameServiceConfigResponse, error) {
	out := new(GameServiceConfigResponse)
	err := c.cc.Invoke(ctx, "/game_service_config.NotifyService/Notify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifyServiceServer is the server API for NotifyService service.
type NotifyServiceServer interface {
	Notify(context.Context, *GameServiceConfigRequest) (*GameServiceConfigResponse, error)
}

// UnimplementedNotifyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNotifyServiceServer struct {
}

func (*UnimplementedNotifyServiceServer) Notify(ctx context.Context, req *GameServiceConfigRequest) (*GameServiceConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}

func RegisterNotifyServiceServer(s *grpc.Server, srv NotifyServiceServer) {
	s.RegisterService(&_NotifyService_serviceDesc, srv)
}

func _NotifyService_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GameServiceConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/game_service_config.NotifyService/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).Notify(ctx, req.(*GameServiceConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NotifyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "game_service_config.NotifyService",
	HandlerType: (*NotifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _NotifyService_Notify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game_service_config.proto",
}
